schombert/Project-Alice

src/gamestate/system_state.cpp
src/gamestate/system_state.hpp
src/gui/gui_element_base.hpp
src/gui/gui_graphics.cpp
src/map/map.cpp
src/map/map.hpp
src/window/window_nix.cpp
src/window/window_win.cpp

Add an initial implementation of panning the map with the middle mouse button held down. At the moment it's a little bit choppy / jank, will probably need fine tuning.

Add middle mouse button panning

---

src/gamestate/system_state.cpp
src/gui/gui_graphics.hpp
src/gui/gui_minimap.hpp
src/gui/gui_production_window.hpp
src/gui/gui_topbar.hpp

The only functionality of the tab itself that is implemented is the close button. Also, right now all sub-tabs are rendered at once so it's a visual mess.

Add production tab

---

src/gui/gui_minimap.hpp
src/map/map.hpp

They don't actually do anything of course.

Implement mapmode buttons

---

src/gui/gui_element_types.hpp
src/gui/gui_production_window.cpp
src/gui/gui_production_window.hpp
src/main.cpp

Commented out list boxes since they cause segfaults, presumably because the list box type hasn't been made yet.

Separate tabs in production window

---

src/gamestate/dcon_generated.txt
src/text/fonts.cpp

gfm refuses to load, yes it needs that many political parties and modifiers, and yes it requires that many leader traits

Make mod work & Scale text appropriately

---

src/map/map_modes.cpp

The colors are generated by hashing the state id. The result is color puke but it's not too far off the original game.

First pass at a regions map mode

---

src/map/map.cpp

Fixed two scrolling bugs, 'grey map bug' and 'inverted map bug'. Also made scrolling consistent.

Fixed two scrolling bugs.

---

src/map/map.cpp

Condensed on_mouse_wheel code.

Condensed on_mouse_wheel code.

---

assets/shaders/map_political_close_f.glsl
assets/shaders/map_political_far_f.glsl
src/gamestate/system_state.cpp
src/map/map.cpp
src/map/map.hpp

Clicking on the map selects a province and the selected province is highlighted. No highlighting on the terrain map mode yet. Also didn't take into account whether the province is water appropriately yet.

Make the map clicky

---

src/gamestate/system_state.cpp
src/gamestate/system_state.hpp
src/gui/gui_element_base.hpp
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/gui_graphics.cpp
src/gui/gui_graphics.hpp

This should fix the broken scrollbars.

Pass relative mouse location from impl_mouse_probe

---

src/map/map_modes.cpp

Also made the green end of the gradient a bit darker.

Fix population map mode

---

src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp

Includes support for colors and preliminary support for scrolling.

Add multiline text boxes

---

src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp

Implemented some substitution options and
compute hyperlink positions.

Implement some missing multiline text features

---

src/gamestate/system_state.cpp
src/gui/gui_graphics.hpp
src/gui/gui_province_window.hpp
src/map/map.hpp
src/parsing/nations_parsing.cpp

Some of the text will actually show what it's meant to show. Also fixed a bug(?) with how the national identity parser fetches localized strings for country name and adjective.

Add province view window

---

assets/shaders/line_border_v.glsl
assets/shaders/map_v.glsl
src/gamestate/system_state.cpp
src/map/map.cpp
src/map/map.hpp

Fixed the map being offset ~25% to the right and fixed the province_highlight texture being too large.

Fix province selection bugs

---

src/gui/gui_console.cpp
src/gui/gui_console.hpp
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/topbar_subwindows/politics_subwindows/gui_decision_window.hpp
src/gui/topbar_subwindows/politics_subwindows/gui_release_nation_window.hpp

Theoretically supports scrolling. Implemented the console output box as a demo. I may have abused templates too much here, but I think the resulting interface is decent.

Add basic list boxes

---

src/gui/gui_console.cpp
src/gui/gui_graphics.hpp
src/gui/gui_topbar.hpp
src/text/text.cpp
src/text/text.hpp
src/window/window_nix.cpp

Tag command works the same as the original game.

Add speed controls and tag command

---

src/gui/gui_console.cpp
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/gui_province_window.hpp
src/gui/gui_topbar.hpp

Also reimplemented tag switching.

Draw flags, add country info to province view

---

src/map/map_modes.cpp

Including the version from OpenV2 that shows the diaspora of a culture when a province is selected, because I think it's neat. Hopefully it's not too much of a deviation from the original game to be included.
Also touched up the innards of the population map mode slightly.

Add nationality map mode.

---

docs/tags_and_flags.md
src/culture/culture.cpp
src/culture/culture.hpp
src/gamestate/dcon_generated.txt
src/gamestate/system_state.hpp
src/ogl/opengl_wrapper.cpp
src/ogl/texture.cpp
src/parsing/parsers_declarations.cpp

Separated this from the "other" big PR... should be mergeable now :)

Non-vanilla flags

---

assets/alice.gui
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/gui_province_window.hpp

Implemented the flags box for spheres in the province view to demo the functionality.

Add overlapping elements box

---

src/gamestate/system_state.cpp
src/gamestate/system_state.hpp
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/gui_province_window.hpp
src/nations/nations.cpp
src/nations/nations.hpp
src/text/text.cpp
src/text/text.hpp

Implemented the following: workforce chart,
ideology chart, population count, cores list.

Implement more province view stuff

---

src/gui/gui_province_window.hpp

RGO icons, culture chart and population for colony view.

Add yet more stuff to province window

---

src/map/map_modes.cpp

Added a global and province sphere map mode.
Need to fix the province colors in the province mode and also add dashed province painting (also needed for culture map)

Add global and province sphere map mode.

---

src/gui/gui_common_elements.hpp
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/gui_province_window.hpp

Implemented the following: terrain image, controller flag, pop icons, flashpoint indicator. Also hid some stuff that can't be meaningfully implemented yet.

Implement basic province header functionality

---

src/entry_point_nix.cpp
src/main.cpp
src/text/bmfontgl/lodepng.cpp
src/text/bmfontgl/stdio.cpp
src/text/fonts.cpp
src/text/fonts.hpp

Also made a couple annoying warnings go away.

Fix errors in lodepng on Linux

---

src/gui/gui_common_elements.hpp

Tooltips for population/supply/employment RGOs/crime

---

src/gui/gui_common_elements.hpp
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/gui_topbar.hpp
src/gui/topbar_subwindows/gui_politics_window.hpp
src/nations/nations.cpp
src/nations/nations.hpp

Implemented national value icon, pluralism, revanchism, government name, indicators for ability to enact political or social reforms, upperhouse data, peoples' ideologies chart.

Fill in basic data for Politics tab

---

src/gui/gui_common_elements.hpp
src/gui/topbar_subwindows/gui_politics_window.hpp
src/nations/nations.cpp
src/nations/nations.hpp

Added the window for the ruling party and the party selection window. Also made the unciv reforms window show up when appropriate.

Display political party data

---

docs/file_system_wrapper.md
src/filesystem/simple_fs.hpp
src/filesystem/simple_fs_nix.cpp
src/filesystem/simple_fs_types_nix.hpp
src/filesystem/simple_fs_types_win.hpp
src/filesystem/simple_fs_win.cpp
src/parsing/parser_defs.txt
src/parsing/parsers_declarations.cpp
src/parsing/parsers_declarations.hpp
tests/scenario_building.cpp

Adds the mechanism for which `replace_path` on .mod files work, I've only tested on Linux but it should work on Windows...
Fixes issues with text going weird on HFM.

Add .mod file support

---

src/culture/politics.cpp
src/culture/politics.hpp
src/gui/gui_common_elements.hpp
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/topbar_subwindows/gui_politics_window.hpp
src/main.cpp

Using a stub for determining the weight of votes

Add voter ideologies chart

---

src/gui/gui_common_elements.hpp
src/gui/gui_element_base.hpp
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp

~draft because it doesn't work, and isn't the entirety of what I am aiming for here~

Pie chart refactor, tooltips

---

src/common_types/date_interface.hpp
src/culture/politics.cpp
src/culture/politics.hpp
src/gui/gui_common_elements.hpp
src/gui/gui_topbar.hpp
src/gui/topbar_subwindows/gui_politics_window.hpp
src/gui/topbar_subwindows/politics_subwindows/gui_reforms_window.hpp
src/gui/topbar_subwindows/politics_subwindows/gui_unciv_reforms_window.hpp

Also added next election start date to government description text.
Still need to disable buttons based on whether the reform can be enacted or not.

Implement reforms windows

---

src/culture/culture.hpp
src/gui/topbar_subwindows/gui_technology_window.cpp
src/gui/topbar_subwindows/gui_technology_window.hpp
src/main.cpp

add technology windowadd technology windowadd technology windowadd technology window

add technology window

---

src/gamestate/dcon_generated.txt
src/gamestate/serialization.hpp
src/gui/gui_common_elements.hpp
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/topbar_subwindows/gui_diplomacy_window.hpp
src/gui/topbar_subwindows/gui_technology_window.cpp
src/gui/topbar_subwindows/gui_technology_window.hpp
src/map/modes/sphere.hpp
src/nations/nations.cpp
src/nations/nations.hpp
src/parsing/parser_defs.txt
src/parsing/parsers_declarations.cpp
src/parsing/parsers_declarations.hpp

fill diplomacy window and some extra stuff on technology tab

fill diplomacy window and some extra stuff on technology

---

src/gui/gui_common_elements.hpp
src/gui/gui_element_types.cpp
src/gui/gui_province_window.hpp
src/gui/topbar_subwindows/gui_budget_window.hpp
src/gui/topbar_subwindows/gui_diplomacy_window.hpp
src/gui/topbar_subwindows/gui_production_window.hpp
src/gui/topbar_subwindows/production_subwindows/gui_invest_brow_window.hpp
src/nations/nations.cpp
src/nations/nations.hpp

investment window country list, tarriffs %, and fixes

---

src/gamestate/dcon_generated.txt
src/gui/gui_province_window.hpp
src/gui/topbar_subwindows/gui_budget_window.cpp
src/gui/topbar_subwindows/gui_budget_window.hpp
src/gui/topbar_subwindows/gui_diplomacy_window.hpp
src/main.cpp

Budget satisfaction Piechart +misc stuff

---

src/parsing/gui_graphics_parsers.cpp
src/parsing/parser_defs.txt
src/parsing/parsers_declarations.hpp

causes hfm to not load gui files

fix maxwidth and maxheight not being known with hfm

---

src/culture/politics.cpp
src/culture/politics.hpp
src/gui/gui_common_elements.hpp
src/gui/gui_element_types.cpp
src/gui/topbar_subwindows/politics_subwindows/gui_movements_window.hpp
src/gui/topbar_subwindows/politics_subwindows/gui_release_nation_window.hpp
src/gui/topbar_subwindows/politics_subwindows/gui_unciv_reforms_window.hpp

Also implemented the reform multiplier icons

Add movements list

---

src/economy/economy.cpp
src/economy/economy.hpp
src/gui/gui_common_elements.hpp
src/gui/topbar_subwindows/gui_trade_window.hpp

Also populated some of the rows in the other listboxes.

Add needs listboxes to trade window

---

src/gui/gui_console.cpp

- tells the user when they made a mistake (and tries to point them to the correct tag, for example)
- generally more user friendly
- stats command added (useful for mods and whatnot)
- fne,ffn,fpe,fpn commands to fire events (gui-side at the moment)
- more resillient to typos and mistakes in general (i.e not crash when the user does something wrong)
- extensible

Improve console window

---

src/entry_point_win.cpp

Does what it says on the box through the ever helpful Windows Registry.

Automatically Detect Victoria 2 for most Windows Users

---

assets/alice.gui
docs/game_loop_basics.md
src/gamestate/system_state.cpp
src/gui/gui_element_types.cpp
src/gui/gui_graphics.hpp
src/gui/gui_main_menu.cpp
src/gui/gui_map_icons.hpp
src/map/map.cpp
src/map/map.hpp

TODO: position widgets correctly on the map, for now they're way off

add units to the map

---

assets/alice.gui
docs/game_loop_basics.md
src/gamestate/system_state.cpp
src/gui/gui_element_types.cpp
src/gui/gui_graphics.hpp
src/gui/gui_main_menu.cpp
src/gui/gui_map_icons.hpp
src/map/map.cpp
src/map/map.hpp

As you scroll out they drift toward the center of the screen, not sure what that's caused by.

Map icons PR with position generally fixed

---

docs/contributing.md

Made some changes to the contributing.md document. Should be a bit more detailed on how to build the game.

Wrote build guide for Linux

---

src/culture/culture.hpp
src/gamestate/dcon_generated.txt
src/ogl/opengl_wrapper.cpp
src/ogl/texture.cpp
src/parsing/parsers_declarations.cpp

some new flags to accommodate the new government types introduced
(and i thought i added most of the flag_types already - apparently not)

extra flag types for coe-roi and aoe

---

src/gamestate/dcon_generated.txt

increment space for mods

---

src/gui/gui_common_elements.hpp
src/gui/gui_element_types.cpp
src/gui/gui_map_icons.hpp
src/gui/gui_province_window.hpp
src/gui/topbar_subwindows/gui_population_window.hpp

draft pop details window

---

src/gamestate/dcon_generated.txt
src/gui/gui_common_elements.hpp
src/gui/topbar_subwindows/gui_budget_window.hpp
src/gui/topbar_subwindows/gui_population_window.hpp

i am so sorry performance, but some sacrifices needs to be done, modding is the most important part of human civilization :>

fix crash for mod

---

src/gui/gui_element_types.hpp
src/gui/topbar_subwindows/gui_population_window.hpp

nicolas coppernico approves of these sacred filters.

pop filters

---

src/gui/gui_common_elements.hpp

Added Tooltips for:
Mobilisation Count,
Leadership Points,
Ships (Perhaps wrong thing?),
Regiment count,
Diplo Point count,
Militancy Count,
Consciousness Count,
and made a wip tooltip for National Focuses and Literacy.

Added Tooltips for topbar

---

src/gamestate/system_state.cpp
src/gui/topbar_subwindows/gui_diplomacy_window.hpp
src/gui/topbar_subwindows/gui_population_window.hpp
src/gui/topbar_subwindows/gui_production_window.hpp
src/gui/topbar_subwindows/politics_subwindows/gui_unciv_reforms_window.hpp
src/gui/topbar_subwindows/production_subwindows/gui_invest_brow_window.hpp
src/gui/topbar_subwindows/production_subwindows/gui_projects_window.hpp

- fix unciv reforms window
- projects window (draft but should be ok to merge)
- fix investment window country list
- implement pop window sort buttons

various UI tinkering

---

src/gui/topbar_subwindows/gui_diplomacy_window.hpp
src/gui/topbar_subwindows/gui_population_window.hpp

- fixes a crash with the pop tab on linux
- add sorting for diplo tab (no gp sort yet)

sorting for diplomacy and pop tab

---

src/gamestate/system_state.cpp
src/gui/gui_main_menu.cpp
src/gui/topbar_subwindows/gui_technology_window.hpp

Also changed the tooltip font as requested in the Discord

Improve technology window tooltips

---

src/gui/gui_outliner_window.hpp

fixes issue with outliner looking wrong

update outliner when checkbox is clicked

---

src/gamestate/system_state.hpp
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/gui_topbar.hpp
src/nations/nations.cpp

Added simple caching for player income over the last 30 days, feel free replace with something better if it's not what you had in mind.

Add line graph element, budget line graph

---

docs/rules.md
src/economy/economy.cpp
src/economy/economy.hpp
src/gamestate/commands.cpp
src/gamestate/commands.hpp
src/gamestate/dcon_generated.txt
src/gui/topbar_subwindows/diplomacy_subwindows/gui_diplomacy_actions_window.hpp

still need to implement nations "giving" each other stockpiles for war subsidies to function properly

increase relations and war subsidies command

---

src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/gui_topbar.hpp
src/gui/topbar_subwindows/gui_budget_window.hpp

Improved the piechart colors and made the chart tooltips work properly. Also fixed the decrease speed button having the wrong tooltip.

Improve budget piecharts, add pop lists

---

src/gui/gui_topbar.hpp

infamy limit text.hpp

---

assets/alice.csv
assets/alice.gui
src/gamestate/serialization.hpp
src/gamestate/system_state.hpp
src/gui/gui_element_types.cpp
src/gui/gui_main_menu.cpp
src/gui/gui_main_menu.hpp

fudged line is toggleable option

---

docs/mods.md
src/gamestate/modifiers.hpp
src/gui/gui_common_elements.hpp
src/gui/gui_element_types.hpp
src/gui/gui_modifier_tooltips.cpp
src/gui/gui_topbar.hpp

"which modifiers affect this" tooltip

---

src/gamestate/modifiers.hpp
src/gui/gui_common_elements.hpp
src/gui/gui_modifier_tooltips.cpp
src/gui/gui_topbar.hpp
src/gui/topbar_subwindows/gui_diplomacy_window.hpp
src/gui/topbar_subwindows/gui_technology_window.hpp

Provides more information than usual :x

More modifier explaination tooltips

---

src/gui/topbar_subwindows/gui_military_window.hpp
src/gui/topbar_subwindows/military_subwindows/gui_build_unit_large_window.hpp
src/gui/topbar_subwindows/military_subwindows/gui_units_window.hpp

- disable not activated units
- show units that are being constructed
- rework so `set` is gone foreva

military window work

---

src/gui/topbar_subwindows/diplomacy_subwindows/gui_declare_war_window.hpp
src/gui/topbar_subwindows/diplomacy_subwindows/gui_diplomacy_actions_window.hpp

fixed country and state list not showing up

state and country list w justify

---

docs/triggers.md
src/gui/gui_event.cpp
src/gui/gui_event.hpp
src/gui/gui_topbar.hpp
src/gui/topbar_subwindows/production_subwindows/gui_commodity_filters_window.hpp

- good filters on prod tab are like in the og
- extra trigger documentation cuz why not
- og event windows

some faithful work

---

.gitignore
src/gui/gui_unit_panel.hpp

Add Some Tooltips to Unit Select Window.
Updated .gitignore to ignore folders build* in top directory.

Add Some Tooltips to Unit Select Window

---

assets/alice.csv
docs/ai.md
src/ai/ai.cpp
src/entry_point_nix.cpp
src/entry_point_win.cpp
src/gui/topbar_subwindows/diplomacy_subwindows/gui_diplomacy_actions_window.hpp

- better decision making
- code duplication removal
- small documentation effort
- allow OPMs to play :3

Ai revision

---

docs/rules.md
src/ai/ai.cpp
src/gamestate/diplomatic_messages.cpp
src/gamestate/system_state.cpp
src/gui/gui_element_types.cpp
src/gui/gui_topbar.hpp
src/military/military.cpp
src/military/military.hpp
src/nations/nations.cpp
src/provinces/province.cpp

-fix ai violating constraints when joinin' war
-fix war continuining even after combatant is ded

-fix topbar bug with politics window

---

assets/shaders/map_f.glsl
src/map/map.cpp

pleseant map shaders

---

src/map/map.cpp

State borders now appear after entering zoomed in view

Adjusted state view

---

SaveEditor/save_editor_main.cpp
assets/alice.csv
src/entry_point_nix.cpp
src/entry_point_win.cpp
src/gamestate/commands.cpp
src/gamestate/commands.hpp
src/gui/gui_graphics.hpp

commands with less misleading and tabloid names

---

src/window/window_nix.cpp

prevents funny stuff like this

enforce minimum window size (linux)

---

src/gamestate/commands.cpp
src/gamestate/commands.hpp

simply separates from the loop of commands and allows us to specify a single command to execute

execute single command function

---

src/gamestate/system_state.cpp
src/parsing/parser_defs.txt
src/parsing/parsers_declarations.cpp
src/parsing/parsers_declarations.hpp

used mainly for "setup" of countries (tgc,hpm,etc)

support `decision = <decision-name>` on country history files

---

CMakeLists.txt
DbgAlice/CMakeLists.txt
DbgAlice/dbg_alice_main.cpp
src/entry_point_win.cpp

dbgalice to debug aborts

---

src/ai/ai.cpp

I tested this, rebels don't pop up until 1850. I think this is a good step towards preventing angery population.

fix ai letting militancy go whoopsie oopsie

---

src/ai/ai.cpp

this really helps combat militancy
prussia will go liberal and everyone goes liberal, this makes pops happy until mid-late-game where it all hits the fan because pop growth kinda too much
hiowever the nations are seemingly more stable now :D

change parties if pops want it

---

docs/project_alice_modders_suggestions.md

leave ur thoughts in the comments below!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Kiwi Modding Suggestions

---

assets/alice.csv
src/gui/gui_effect_tooltips.cpp
src/gui/topbar_subwindows/politics_subwindows/gui_decision_window.hpp
src/parsing/effect_parsing.hpp
src/parsing/parsers_declarations.cpp
src/parsing/provinces_parsing.cpp
src/scripting/effects.cpp
src/scripting/script_constants.hpp

- annex_to = null added for countries and provinces

VU fork fixes

---

assets/alice.csv
src/gamestate/system_state.cpp
src/gui/gui_graphics.hpp
src/gui/topbar_subwindows/gui_technology_window.hpp

right -> remove tech
shift -> add tech to queue

Technology queue

---

src/culture/culture.cpp
src/economy/economy.cpp
src/gamestate/cheats.cpp
src/gamestate/cheats.hpp
src/gamestate/commands.cpp
src/gamestate/commands.hpp
src/gamestate/diplomatic_messages.cpp
src/gamestate/notifications.cpp
src/gamestate/system_state.hpp
src/gui/gui_console.cpp

- instant research
- instant construction
- always accept deals (yesman)
- always enact reforms
- always add wargoals
- toggle ai on/off

cheat commands

---

src/gamestate/dcon_generated.txt
src/parsing/effect_parsing.cpp
src/parsing/nations_parsing.cpp

- increment modifier size
- fix newlines on errors for effects

extra space for modifiers (gfm)

---

assets/alice.gui
src/parsing/parser_defs.txt
src/parsing/parsers_declarations.hpp

allow shortening `position ={ x = 5 y = 6 }` to `position = { 5 6 }` like in modern titles

allow free gfx pairs

---

src/military/military.cpp

state.world.leader_get_since(l).to_raw_value() is already amount of days that leader exists

Fixed the bug that new leaders die almost instantly

---

src/gui/topbar_subwindows/military_subwindows/gui_build_unit_large_window.hpp
src/military/military.cpp
src/parsing/defines.hpp

I like the option of being able to toggle it on/off

make full reinforcement moddable

---

assets/alice.csv

also fixes some wrong text on nation picker

update csv keys to mp branch

---

assets/alice.csv
src/gamestate/commands.cpp
src/gamestate/commands.hpp
src/gui/topbar_subwindows/diplomacy_subwindows/gui_diplomacy_actions_window.hpp
src/gui/topbar_subwindows/gui_diplomacy_window.hpp

Release puppet action

---

docs/pt/about.md
docs/pt/contributing.md

Add some Portuguese translations of the docs

---

CMakeLists.txt
src/main.cpp
src/network/network.cpp
src/network/network.hpp

Network stubs

---

assets/alice.gui

makes spacing more uniform for all the tabs

Improve spacing for main menu

---

assets/alice.gui
assets/shaders/msaa_f_shader.glsl
assets/shaders/msaa_v_shader.glsl
src/gamestate/system_state.cpp
src/gamestate/system_state.hpp
src/gui/gui_main_menu.cpp
src/gui/gui_main_menu.hpp
src/map/map.cpp
src/ogl/opengl_wrapper.cpp
src/ogl/opengl_wrapper.hpp
src/ogl/opengl_wrapper_win.cpp
src/window/window_nix.cpp

AA implemented, with options to go from 0, 1, 2, 3, 4, etc
User controlled via main menu, defaults to 0.

Implement antialiasing setting

---

docs/multiplayer.md
src/gamestate/commands.cpp
src/gamestate/commands.hpp
src/gamestate/system_state.hpp
src/gui/gui_console.cpp
src/gui/topbar_subwindows/diplomacy_subwindows/gui_diplomacy_actions_window.hpp

- remove redundant command
- miscellaneous fixes

Misc. fixes and updates

---

src/gamestate/system_state.cpp
src/parsing/military_parsing.cpp
src/parsing/parsers_declarations.cpp

- show filename where invalid unit type was found for unit
- oob relationships within range

improve error reporting

---

CMakeLists.txt
dependencies/tbb/CMakeLists.txt
src/sound/sound_nix.cpp

- Removed _FORTIFY_SOURCE flag from debug build, since it also requires adding -O2
- Added missing '-mwaitpkg' flag to the compilation of tbb
- Removed unnecessary '-stdlib=libc++'
- Fixed sound function trying to access the wrong struct

Fix Linux Build

---

assets/alice.csv
src/gamestate/commands.cpp
src/gamestate/system_state.cpp
src/network/network.cpp

- csv keys
- yes we dont want to break mp

Leftover map visual stuff that i didnt manage to merge in time

---

src/gamestate/dcon_generated.txt

allows me to actually play the game for a while after 1844,

increment army size (zombie mod, related to rebels)

---

src/ai/ai.cpp

prevents prussia from losing their substates to rebels [in TGC]
and china too

take care of vassals and substates

---

src/gui/gui_graphics.hpp

I TOOK A HEX EDITOR AND COMAPRED TWO DUMPS (OF RAW SCENARIO DATA NOT JUST THE DCON PART) AND THEN I FOUND OUT THAT THE GFX WAS GOING WILD SHIT AJSDKLGJNDFGKH

FIX PADDING ON GFX OBJECTS CAUSING ISSUES

---

src/map/map.cpp

unsure if you are willing to merge this as-is through, if not, then could we make this a setting? 🥺 
note: font unrelated, pr only change map, not font or text

More v2-looking map

---

assets/alice.csv
src/gui/topbar_subwindows/gui_diplomacy_window.hpp

war start date display

---

src/gui/gui_element_types.hpp
src/gui/gui_event.cpp
src/gui/topbar_subwindows/gui_politics_window.hpp
src/gui/topbar_subwindows/gui_technology_window.hpp

makes mods like CWE behave better with text

black and white font fixes for text

---

assets/alice.csv
src/gamestate/commands.cpp
src/gamestate/commands.hpp
src/gamestate/diplomatic_messages.cpp
src/gamestate/diplomatic_messages.hpp
src/gui/gui_diplomacy_request_window.hpp
src/gui/topbar_subwindows/diplomacy_subwindows/gui_diplomacy_actions_window.hpp
src/gui/topbar_subwindows/gui_diplomacy_window.hpp

Implement multiplayer state transfers

---

src/map/map.cpp

makes the map on higher levels look nicer

render impassable borders on higher zoom levels

---

assets/alice.csv

Saw it missing from a terrain bonuses tool tip.

Add missing CSV entry

---

src/map/map_data_loading.cpp

Complains about `std::max(int, uint32_t)`.

Fix compiler error

---

src/economy/economy.cpp

omg i can go to 1845 in lightspeed

optimization bringing down 15~ secs per minute to 3~ secs per minute

---

src/common_types/SPSCQueue.h

Update SPSCQueue.h to newest from 4 months ago

---

src/economy/demographics.cpp
src/economy/economy.cpp
src/gamestate/commands.cpp
src/gamestate/dcon_generated.txt
src/gamestate/serialization.hpp
src/gamestate/system_state.cpp
src/gui/gui_topbar.hpp
src/gui/topbar_subwindows/gui_diplomacy_window.hpp
src/nations/nations.cpp
src/parsing/parsers_declarations.cpp
src/provinces/province.cpp
src/scripting/effects.cpp
src/scripting/triggers.cpp

1.leaving this for review mainly
2.i will provide measurements of tests later

accepted_cultures becomes a bitfield

---

src/entry_point_win.cpp

reasons why have headless mode:
a) test in vtune performance improvments without the noise from opengl drivers
b) the public server idea

headless mode

---

src/map/map_state.cpp
src/map/map_state.hpp

using std::chrono::system_clock for timing stuff could lead to funnies

change uses of system_clock to steady_clock

---

src/entry_point_win.cpp

as requested in feature requests

Continual looping mode for benchmark/stability/stress testing computer

---

docs/multiplayer.md
docs/rules_es.md

I translated the entire rules.md document into Spanish.

Spanish Translation of Rules

---

assets/alice.csv
src/gui/topbar_subwindows/diplomacy_subwindows/gui_pick_wargoal_window.hpp
src/gui/topbar_subwindows/gui_technology_window.hpp

display chance of discovering an invention on hovering its name

---

docs/Devlogs/november/november_es.md

Spanish translation of november

---

docs/de-de/contributing.md

(Yes, Schombert, I also know some German lol)

German translation

---

assets/alice.csv
assets/alice.gui
src/gui/topbar_subwindows/gui_trade_window.hpp

and add a few helpful tooltips to other buttons:tm:

nudge some trade window buttons

---

src/ai/ai.cpp

- AI will now not account relations on selecting rivals (it fixes AI just rivalling kinda nobody)
- AI now will seek to justify on nations that are at war; this such that it can take advantage of the war of a nation
- It will also no longer attempt multicontinental invasions without first asserting it has naval supremacy (can defeat the target navy) AND that it has a navy to begin with (hence the min)

AI justify on more sensical (AND viable targets)

---

src/map/map_state.cpp

as the title says, add the ability to move the map with the cursor
used same logic as using the arrows to move

move map with cursor

---

src/launcher/launcher_main.cpp

Nobody wants to mod the launcher, they want to mod the game - and it makes it a bit easier to separate the launcher from the main game, especially when we change the shaders

put opengl shaders directly in launcher

---

assets/alice.csv
src/gui/gui_element_types.cpp
src/gui/gui_element_types.hpp
src/gui/topbar_subwindows/gui_budget_window.hpp
src/gui/topbar_subwindows/gui_trade_window.hpp

ok i cant do ctrl cuz its too hard, have shift-right-click instead

Add shift-right-click for max slidering performance

---

src/gui/gui_chat_window.hpp

more compact chat window

---

src/gui/gui_common_elements.hpp
src/gui/gui_province_window.hpp
src/gui/gui_topbar.hpp
src/gui/topbar_subwindows/gui_diplomacy_window.hpp

Added a red military score icon when it's mobilized

---

src/entry_point_nix.cpp
src/gamestate/commands.cpp
src/gamestate/commands.hpp
src/network/network.cpp

set player on AI (with make_ai parameter for command too)

---

src/text/fonts.cpp

Still a 64bit processor so yes, 64 bit no popcount, wonders

Fix popcnt causing crashes on Penryn processors

---

docs/extensions.md
src/parsing/effect_parsing.hpp
src/parsing/parser_defs.txt

sugar variable syntax for ahmp

---

docs/extensions.md
src/gamestate/system_state.cpp
src/parsing/parsers_declarations.hpp
src/parsing/provinces_parsing.cpp

will greatly reduce the number of files in AHMP - making the rar compression better :D

specify province history in csv

---

src/gamestate/dcon_generated.txt
src/gui/topbar_subwindows/politics_subwindows/gui_reforms_window.hpp
src/gui/topbar_subwindows/politics_subwindows/gui_unciv_reforms_window.hpp
src/parsing/cultures_parsing.cpp

A small addition for AHMP flavour

add reform desc

---

assets/alice.csv
src/gui/gui_element_types.hpp
src/gui/gui_topbar.hpp
src/gui/topbar_subwindows/gui_budget_window.hpp
src/gui/topbar_subwindows/gui_politics_window.hpp

- better slider button description tooltips
- add modifier descriptions in relevant places (especially the budget screen)
- fix a bug where reform names are shown twivce in party desc

misc improvments to UI

---

src/ai/ai.cpp

- do not liberate our own territory (i.e russia liberating siberia from russia)
- do participate on the side of liberating territory against someone
- shoot the other side if we can

Fix AI behaviour on crisis

---

src/network/network.cpp

State sponsored companions no longer exist

Fix some players becoming the same nation as another client

---

assets/alice.csv
src/gui/gui_topbar.hpp

not even vanilla displays them lmao

Fix tooltip for shortcut not showing on pause button and tabs

---

src/gui/topbar_subwindows/gui_budget_window.hpp
src/text/text.cpp

- use () for negative numbers
- colour every number, in dark tones of course :)

Stylize budget tab to be like an accounting report

---

src/gui/topbar_subwindows/gui_budget_window.hpp
src/text/text.cpp

more fixes to prettify

---

src/gui/gui_unit_panel.hpp
src/gui/gui_unit_panel_subwindow.hpp

Sort regiments and ships by type

---

src/gui/gui_diplomacy_request_topbar.hpp

fix flag button absorbing click events on the diplomatic message topbar stuff

---

assets/alice.csv
assets/alice.gui
src/ai/ai.cpp
src/gamestate/commands.cpp
src/gamestate/commands.hpp
src/gamestate/dcon_generated.txt
src/gui/gui_unit_panel.hpp
src/gui/topbar_subwindows/gui_military_window.hpp
src/military/military.cpp

Mobilized units become AI controlled (toggle)

---

src/text/text.cpp

fix text display again

---

src/launcher/launcher_main.cpp

add #include "gui_error_window.cpp" to launcher

---

src/launcher/launcher_main.cpp

limit ip address field to something more reasonable

---

src/gui/topbar_subwindows/diplomacy_subwindows/gui_peace_window.hpp

avoid some irritating experiences of sending WP when we dont intend to

All wargoals selected by default on peace window

---

src/launcher/launcher_main.cpp

a surprising amount of people do read, and believe this is a fatal error
this will remove a quite few tickets off tech-support

Tell user scenario errors are not nescesearily fatal

---

src/map/map.cpp

fixes floor for factory xac and railroad stations

xac floor fix

---

src/map/map.cpp

good for contrast and locating stuff, when even the "tilting" highlight is not enough

Show outline of selected nation/province

---

src/sound/sound_nix.cpp
src/sound/sound_win.cpp

fixes for The Grand Orchestra

---

src/gui/gui_element_types.cpp

missing fonts will no longer cause a crash, now it will give visual indication of the lack thereof

Stop line height being 0 crashing alice

---

src/gui/map_tooltip.cpp

Tooltip fix when nations are with 0 pops

---

src/gamestate/serialization.hpp

just learned in an MP game we should bump version lol

bump save version

---

src/gamestate/system_state.cpp

get_full_name -> get_file_name

---

src/map/map.cpp

Make map font smaller

---

src/map/map.cpp

This makes better contrast for low zooms
and also makes the hover look prettier

Show national borders in black and hovers in white

---

src/parsing/parser_defs.txt

discovered by mere experimentation
(vanilla)

diplomatic_decisions alias

---

src/gamestate/system_state.cpp

Fix units detail box not working

---

src/parsing/parsers_declarations.cpp

Not an error -> make it a warning!

Make defining pops with rebels on uncolonized provinces be a warning

---

src/gamestate/system_state.cpp

Make inventions active at start date

---

src/gui/gui_effect_tooltips.cpp
src/parsing/effect_parsing.cpp
src/scripting/effects.cpp
src/scripting/script_constants.hpp

Fixes renaming decision on pauils branch of gfm

Renaming fused op

---

src/gamestate/cheats.cpp
src/gamestate/cheats.hpp
src/gamestate/commands.cpp
src/gamestate/commands.hpp
src/gui/gui_console.cpp

caopt => clear all auto choice
saopt => set all auto choice

(control auto choice in console) Saopt and Caopt

---

src/map/map.cpp
src/map/map.hpp
src/map/map_state.cpp

red => attack
gray => retreat
like vanilla :3

Coloured arrows like in vanilla

---

src/economy/economy.cpp
src/economy/economy.hpp

- Subsistence system: paid rgo workers now choose between subsistence farming and working to sell their product.
- Add missing multiplier to private education

Few economic improvements.

---

src/graphics/opengl_wrapper_nix.cpp
src/graphics/opengl_wrapper_win.cpp
src/launcher/launcher_main.cpp
src/window/window_win.cpp

as a rule of thumb
we should abort when the state is invalid
not when there was a failure initializing a component

Do not abort on failure of things, just show the error itself

---

assets/alice.csv
dependencies/stb/stb_image_write.h
src/gui/gui_common_elements.cpp
src/gui/gui_common_elements.hpp
src/gui/gui_console.cpp
src/gui/gui_message_filters_window.hpp
src/gui/gui_minimap.hpp
src/gui/topbar_subwindows/gui_diplomacy_window.hpp
src/gui/topbar_subwindows/military_subwindows/gui_build_unit_large_window.hpp
src/gui/topbar_subwindows/production_subwindows/gui_invest_brow_window.hpp

- `dmap` generate map
- some filter QoL additions
- and fixes to existing filters

Generate map on the console with `dmap`, and some fixes for filters

---

src/ai/ai.cpp
src/military/military.cpp
src/parsing/defines.hpp
src/parsing/effect_parsing.cpp
src/parsing/effect_parsing.hpp
src/text/text.hpp

2 GP limit (instead of 3), Renaming not using terrain names, Fix liberated nations not being on sphere

---

assets/localisation/zh-CN/alice.csv
assets/localisation/zh-CN/map.csv
assets/localisation/zh-CN/mapmodes.csv
assets/localisation/zh-CN/messages.csv
assets/localisation/zh-CN/settings.csv

Now we have roughly finished the Chinese translation work. tho it still need to adjust with the effects in game.
Credits: shudorcl(黎塞留公爵) MeizhouWan(🐱骑士) KlangTjews Selee1995(席勒)
Vanilla localization is from [52PCgame](https://bbs.52pcgame.net/)

Update the Chinese localization

---

CMakeLists.txt
assets/alice.gui
assets/localisation/en-US/alice.csv
src/common_types/constants.hpp
src/entry_point_win.cpp
src/gamestate/cheats.cpp
src/gamestate/commands.cpp
src/gamestate/game_scene.cpp
src/gamestate/game_scene.hpp
src/gamestate/system_state.cpp
src/gamestate/system_state.hpp
src/gui/gui_chat_window.hpp
src/gui/gui_common_elements.hpp
src/gui/gui_element_types.cpp
src/gui/gui_error_window.cpp
src/gui/gui_graphics.hpp
src/gui/gui_land_combat.hpp
src/gui/gui_main_menu.cpp
src/gui/gui_map_icons.hpp
src/gui/gui_naval_combat.hpp
src/gui/gui_unit_panel.hpp
src/gui/map_tooltip.cpp
src/launcher/launcher_main.cpp
src/main.cpp
src/map/map.cpp
src/military/military.cpp
src/military/military.hpp
src/nations/nations.cpp
src/network/network.cpp

Allows easier set up of new scenes. Lays down foundation for military automation but it requires some work.

UI refactor and military automation foundation.

---

ParserGenerator/parser_generator.cpp

compiler was unable to recognize std::find or std::find_if without including algorithm

fix linux build error

---

src/parsing/provinces_parsing.cpp

before muting me on the discord you shouldve known i already fixed this and more issues, this affects most igor derivates and hfm

Fix infinite/invalid RGOs due to wrongly defined provinces on some mods

---

src/military/military.cpp

fix colonial crisis :)

---

assets/localisation/ar-AR/alice.csv
assets/localisation/en-US/alice.csv
assets/localisation/ru-RU/alice.csv
src/gui/gui_common_elements.hpp
src/gui/gui_unit_panel_subwindow.hpp

Soldiers culture in the tooltip. Table header for RGO and subsistance building tooltip

UI tooltip improvements

---

assets/alice.gui
src/gamestate/system_state.cpp
src/gamestate/system_state.hpp
src/graphics/opengl_wrapper.cpp
src/graphics/opengl_wrapper.hpp
src/gui/gui_element_types.cpp
src/gui/gui_graphics.hpp
src/gui/gui_minimap.hpp
src/gui/gui_unit_panel.hpp
src/text/text.cpp
src/text/text.hpp

Display composition instead of names.
Ability to set up template as main.
Ability to build up stationary army to template.
Implement unit icons as text embeds and clean up some old code.

Template improvemnts.

---

assets/localisation/en-US/alice.csv
docs/extensions.md
src/gamestate/system_state.cpp
src/gui/gui_effect_tooltips.cpp
src/parsing/effect_parser_defs.txt
src/parsing/effect_parsing.hpp
src/scripting/effects.cpp
src/scripting/script_constants.hpp

- Allow using `religion` effect in pop context to change pop's religion.
- Introduce `set_culture` effect to change culture of pop to any culture.

Effects changes, subjects can't become GPs

---

src/economy/economy.cpp
src/economy/economy.hpp
src/gui/topbar_subwindows/gui_trade_window.hpp

Update artisans logic. Recalculate costs of private construction when initiating new buildings.

artisans and construction initiation tweaks

---

src/gamestate/diplomatic_messages.cpp
src/gamestate/diplomatic_messages.hpp
src/gamestate/system_state.hpp

Includes:
sys::state
sys::state::world
diplomatic_message::message
diplomatic_message::post
diplomatic_message::ai_will_accept

Some summaries for common things, for code accessibility.

---

src/economy/economy.cpp
src/gui/gui_province_window.cpp

- Subjects and sphered nations can't tax trade with their superiors anymore
- Tariffs on occupied territory are not collected
- Trade is decided by controller of market capital instead of state owner
- If controller of a port and controller of a capital are different, market is considered blockaded

Changes to tariff collection logic and trade pathing

---

src/ai/ai.cpp

- Improves early game supply of machine parts.

Technology weight tweak

---

src/economy/demographics.cpp

- Prevents migration to countries with both base attraction and global attraction being negative

sanitise usage of global_immigrant_attract

---

src/graphics/texture.cpp
src/gui/gui_map_icons.hpp

Also cleaned up some leftover code (that was commented out, that is)
Also, added an assert that well, asserts that the generic rebel flag was able to be acquired.

Fix rebel flags

---

src/economy/economy.cpp

- Fix bug: province with defined rgo distribution had 0 rgo size which led to 0 subsistence.

Set rgo size for all provinces

---

src/economy/economy_government.cpp
src/economy/economy_government.hpp
src/gui/gui_unit_panel.hpp

fix supply tooltip bug

---

docs/user_guide.md

Update user_guide.md to specify proton compatibility

---

src/culture/culture.cpp
src/culture/culture.hpp
src/gamestate/dcon_generated.txt
src/gamestate/system_state.cpp
src/gamestate/system_state.hpp
src/graphics/opengl_wrapper.cpp
src/graphics/texture.cpp
src/graphics/texture.hpp
src/gui/demographicswindow.cpp
src/gui/gui_element_types.cpp
src/gui/gui_nation_picker.hpp
src/gui/pop_details.cpp
src/parsing/parsers_declarations.cpp
src/parsing/parsers_declarations.hpp
tests/scenario_building.cpp

Extends flags support to arbitrary flag names up to some limit.

rework flags management

---

src/gamestate/game_scene.cpp
src/gamestate/system_state.cpp
src/gui/economy_viewer.cpp
src/gui/gui_map_icons.hpp
src/map/map.cpp
src/map/map_state.cpp
src/map/map_state.hpp

- Fix position of ports icons
- Cull icons outside screen

Minor graphical tweaks

---

assets/alice.gui
assets/localisation/en-US/settings.csv
assets/shaders/glsl/map_f.glsl
assets/shaders/glsl/map_provinces_f.glsl
assets/shaders/glsl/textured_line_b_provinces_f.glsl
assets/shaders/glsl/textured_line_b_v.glsl
src/common_types/constants.hpp
src/gamestate/system_state.cpp
src/gamestate/system_state.hpp
src/graphics/opengl_wrapper.cpp
src/gui/gui_main_menu.cpp
src/gui/gui_main_menu.hpp
src/map/map.cpp
src/map/map.hpp
src/map/map_borders.cpp
src/provinces/province.cpp

- Weave together national borders into coherent loops
- Add support for national border gradients
- Implement graphical settings

Smoother borders and a few graphic features

---

src/ai/ai.cpp
src/military/military.cpp
src/military/military.hpp
src/nations/nations.cpp

1. AI properly research doctrines costing leadership points
2. AI won't ally weak neighbours
3. A bit smarter construction
4. AI army size estimation
5. Remove extra break
6. AI won't upgrade units if shortages

Smarter AI

---

src/ai/ai.cpp
src/economy/economy.cpp
src/economy/economy.hpp
src/economy/economy_production.cpp
src/economy/economy_stats.cpp
src/gamestate/serialization.cpp
src/gui/budgetwindow.cpp
src/gui/gui_console.cpp
src/military/military.cpp
src/nations/nations.cpp

Focuses on improving economy stability and fixes a distance bug

Minor economy changes

---

assets/localisation/en-US/alice.csv
docs/Devlogs/v1.2.3/README.md
docs/extensions.md
src/ai/ai.cpp
src/economy/construction.cpp
src/economy/construction.hpp
src/gamestate/commands.cpp
src/gamestate/dcon_generated.txt
src/gui/topbar_subwindows/gui_production_window.cpp
src/gui/topbar_subwindows/gui_production_window.hpp
src/parsing/defines.hpp
src/parsing/econ_parsing.cpp
src/parsing/parser_defs.txt
src/parsing/parsers_declarations.hpp

With define, allow constructing selected factories in colonies

---

src/economy/construction.cpp

Quick fix which restores functionality of logic which rely on the introduced functions.

Quick fix of colonial check

---

assets/localisation/zh-CN/alice.csv
assets/localisation/zh-CN/settings.csv

Fixed punctuation in 'employment_type_high_education' and added new employment type translations in alice.csv. Added 'disband_confirmation_label' to settings.csv for improved UI localisation.

Update Chinese localisation for employment types and settings

---

assets/localisation/zh-CN/alice.csv

This commit refines punctuation, grammar, and consistency in the CN localization file for Alice, improving clarity and accuracy. It also adds new strings related to population literacy spending and budget explanations, enhancing in-game tooltip coverage for economic and education mechanics.

Improve Chinese localization and add new budget tooltips

---

assets/localisation/zh-CN/alice.csv

Improved spacing and consistency in variable placeholders, standardized phrasing, and enhanced readability across the zh-CN/alice.csv localization file.

Refine Chinese localization for Alice mod

---

src/ai/ai.cpp
src/ai/ai_economy.cpp
src/economy/construction.cpp
src/economy/economy.cpp
src/economy/economy_production.cpp

- Increase money supply as economy was a bit too starved for money
- AI will invest more aggressively
- Change total embargo condition: AI was clueless about this thing being so punishing and was often reaching the threshold ruining its own economy in the process
- Reduce factory costs a bit to compensate for recent economy changes

A set of economy tweaks

---

src/gamestate/system_state.cpp
src/gui/gui_common_elements.hpp
src/gui/gui_context_window.cpp
src/gui/gui_graphics.hpp
src/gui/province_tiles/province_tiles.cpp
src/gui/topbar_subwindows/gui_production_window.cpp
src/gui/topbar_subwindows/gui_production_window.hpp
src/gui/topbar_subwindows/production_subwindows/gui_build_factory_window.hpp

Extract Build Factory Window from Production Window for users to quickly build factories from Province Window and Tiles Window.

Popup build factory window

---

assets/localisation/en-US/alice.csv
src/gamestate/commands.cpp
src/gamestate/commands.hpp
src/gui/gui_common_elements.hpp
src/gui/gui_context_window.cpp
src/gui/gui_context_window.hpp
src/gui/province_tiles/gui_province_tiles_tiles.hpp

Tiles context menu delete factory
Expand construction tooltip
Tiles context menu cancel construction

Expanded Tiles UI
