schombert/Project-Alice

src/gui/gui_element_base.hpp, src/gui/gui_graphics.cpp
If transparencecheck=yes, mouse only counts as over the element if the primary texture's alpha is not 0 at that pixel. Otherwise, if the gfx object has a mask texture, mouse only counts as over the element if the mask alpha at that pixel is not 0.
=> Handle partial transparency and masks when probing mouse

src/gamestate/system_state.cpp
The simple_fs implementation for linux gets the actual extension to compare against the expected including the dot. In other words it was checking `.txt == txt`.
=> Fix pop type loading on linux

src/map/map.cpp, src/map/map_modes.cpp
Restricts to the nation of the selected province when a province is selected. Pretty awkward to use since map modes only update when the map mode changes, will need to make certain map modes update more frequently.
=> Add population map mode

assets/alice.gfx, assets/alice.gui, src/gamestate/system_state.cpp, src/gui/gui_console.cpp, src/gui/gui_element_types.cpp, src/gui/gui_element_types.hpp, src/gui/gui_fps_counter.hpp, src/gui/gui_graphics.cpp, src/gui/gui_graphics.hpp, src/gui/gui_minimap.hpp, src/gui/gui_province_window.hpp, src/gui/gui_search_window.hpp
The FPS Counter is toggled using the `fps` console command.
For the moment, the search / goto window
only searches provinces. Also, I couldn't find the gui
asset for the button used in the province list, so
I made a custom one. I'm fairly confident the button is not
set up "normally", if it is please correct me.
=> Add FPS Counter and search window

src/gui/gui_element_types.cpp, src/gui/gui_element_types.hpp
Known issue: the scroll position doesn't respond immediately when the listbox is resized, so updating the listbox can cause the list to be offscreen. Simply scrolling will fix it.
=> Add listbox scrollbars

src/gui/gui_element_types.cpp
This should make the track better aligned, and prevent the slider from going over the bottom button.
=> Tweak listbox scrollbar scaling

src/gui/gui_element_types.cpp, src/gui/gui_element_types.hpp, src/gui/gui_province_window.hpp
The culture chart is generated in one pass at the expense of cultures being sorted by size in the chart.
=> Add culture chart to province view

assets/shaders/map_political_close_f.glsl, assets/shaders/map_political_far_f.glsl, src/map/map.cpp, src/map/map.hpp, src/map/map_modes.cpp, src/map/map_modes.hpp
The main change is that the province color texture was changed to a Texture Array of 2 textures, the province color and the stripes color.
In gen_prov_color_texture (map.cpp) the prov_color vector was kept, but it contains the colors for both textures, First for province color and then stripe colors.
I'm not quite sure if using a texture array of only 2 textures is better or worse in terms of performance (compared to 2 separated textures).
Initially I thought that with 4 iterations of the stripe texture you could fill the image. I wanted to do 4 color textures to make the map coloring more generic, one for each stripe. But this doesn't work, because the stripes don't have the same size.
For now I modified the culture map to use the stripes, but I'll also need to modify the other map modes
=> Add stripes to map

src/gui/gui_common_elements.hpp, src/gui/gui_console.cpp, src/gui/gui_console.hpp, src/gui/gui_element_types.cpp, src/gui/gui_element_types.hpp, src/gui/gui_topbar.hpp
This also bundles in a fix that prevents typing into console text box when it's closed (and still focused.). Console is now a lot more stable and usable--only thing that needs to be implemented is reestablishing focus on main window once it is closed (add to toggle_console).
Free colonial power always remains at 0, since the function needs implementation. However, if you tag into great powers, you can see their cap.
=> Colonial Power / Tilde to close console.

src/gui/gui_common_elements.hpp, src/gui/gui_element_types.cpp, src/gui/gui_element_types.hpp, src/gui/gui_province_window.hpp, src/gui/topbar_subwindows/gui_politics_window.hpp, src/gui/topbar_subwindows/politics_subwindows/gui_unciv_reforms_window.hpp
Added the progress_bar base type, implemented progress bars for liferating and westernization. Also implemented the progress bar for rgo employment, which is actually a 10 frame image rather than a typical progress bar.
=> Add progress bars

src/gui/gui_element_types.hpp
Should fix clicks passing through the province window.
=> Make text elements eat clicks by default

src/culture/politics.cpp, src/gui/gui_common_elements.hpp, src/gui/gui_element_types.cpp, src/gui/topbar_subwindows/gui_politics_window.hpp, src/text/text.cpp
Fixed the following: text::prettify not handling the millions place correctly, reforms not registering as enactable if they are a get-next-only reform type, cultures sneaking into piecharts where they don't belong.
=> Squash some bugs, formatting tweaks

src/gui/gui_common_elements.hpp, src/gui/topbar_subwindows/politics_subwindows/gui_release_nation_window.hpp, src/nations/nations.cpp
A couple omissions: wasn't sure how to get the type (substate or satellite) of the released vassal, and it seems
national_identity.is_releasable isn't working.
=> Add release nations tab

src/economy/economy.cpp, src/economy/economy.hpp, src/gui/gui_common_elements.hpp, src/gui/topbar_subwindows/gui_budget_window.hpp, src/nations/nations.cpp, src/nations/nations.hpp
Some of the values are using numbers stubbed to 1 and are not representative of reality, most notably the taxes and tariffs.
=> Implement budget window sliders and their value displays

.editorconfig, CMakePresets.json
Requires the user to have the cmake-tools extension installed.
Made building the project (assuming you have all the dependencies) just be a matter of choosing a development profile and building. Currently there are two profiles, x64 release and x64 debug, both built with Clang.
=> Add linux cmake build presets for Visual Studio Code 

src/gui/gui_element_types.cpp, src/gui/gui_element_types.hpp, src/gui/topbar_subwindows/politics_subwindows/gui_decision_window.hpp, src/gui/topbar_subwindows/politics_subwindows/gui_reforms_window.hpp
The scrollable_text element could also be used wherever it makes sense to use.
Also fixed a bug where the reform buttons wouldn't highlight properly, and another where clicks would phase through pie charts.
Also right now this makes scrolling in the decisions menu pretty clunky, but that should be resolved once the scrolling behaviour is reverted to scanning through the ui hierarchy instead of just using the element under mouse.
=> Make decision descriptions scrollable

src/gui/gui_common_elements.hpp
I think this is how generic_settable_element is suppose to work. In that case it is a fix for that too.
=> Fix diplomacy window country name

src/economy/economy.cpp, src/economy/economy.hpp, src/gui/gui_common_elements.hpp, src/gui/gui_console.cpp, src/gui/gui_province_window.hpp, src/gui/topbar_subwindows/diplomacy_subwindows/gui_diplomacy_actions_window.hpp, src/gui/topbar_subwindows/gui_budget_window.hpp, src/gui/topbar_subwindows/gui_diplomacy_window.hpp, src/gui/topbar_subwindows/gui_production_window.hpp, src/gui/topbar_subwindows/production_subwindows/gui_build_factory_window.hpp, src/gui/topbar_subwindows/production_subwindows/gui_commodity_filters_window.hpp, src/gui/topbar_subwindows/production_subwindows/gui_factory_buttons_window.hpp, src/gui/topbar_subwindows/production_subwindows/gui_projects_window.hpp
- fix alignment on projects window with inputs
- show construction factories, the upgrading of factories and the factories normally
- influence diplomacy actions now show a window instead of immediately doing action
- fixed bug with gp selection on diplo window not being used as the affected_gp in influence actions
- fixed crash with console
- fixed colours of budget window
- various production disable buttons if not used
- select/deselect all commodity filters
=> various ui improvments and fixes

CMakeLists.txt
To compile successfully in Windows environments that are not English or Western European.
=> force utf8

src/gui/gui_topbar.hpp
Added button actions opening specified tab when player clicks on the reform, decision, or rebels icon on the topbar.
Working on learning the UI system for PA, I'll be more active cause summer & OV is mid cycle.
=> Add Icon Actions to the Politics Window

src/gui/topbar_subwindows/politics_subwindows/gui_decision_window.hpp
Decision Tooltips were previously switched up, now behaves like vanilla/intended functionality.
=> Fix Decision Tooltips

src/gamestate/system_state.cpp, src/map/map.cpp, src/parsing/effect_parsing.cpp, src/parsing/nations_parsing.cpp, src/parsing/trigger_parsing.cpp
why:
some mods have hundreds and hundreds of invalid and malformed effects and triggers, this causes a **crash** in Project Alice, rather than crashing we would do:
a) emit warning and error messages
b) let the user continue if so they wish
I think a PR like this was submitted very early on, but it didn't have placeholder triggers/effects, here it does have them and it allows most invalid triggers and effects to simply call a "dummy" no-operation trigger.
it evaluates to false, so it never gets executed and doesn't cause a cascade of invalid errors and event chains, etc.
this is mainly for improving the user experience of "it works out of the box" - yes, it means some content will not be accessible due to it having errors - but it will also allow users to experience the content without …
=> placeholder trigger and effects

src/gamestate/serialization.cpp, src/gamestate/serialization.hpp, src/gamestate/system_state.cpp, src/gamestate/system_state.hpp, src/gui/gui_effect_tooltips.cpp, src/gui/gui_trigger_tooltips.cpp, src/gui/topbar_subwindows/gui_technology_window.hpp, src/scripting/effects.cpp, src/scripting/triggers.cpp
Fixes errors with various "big" mods like GFM and TGC. The issue is that most effects are indeed valid, however they are put way beyond the 64K barrier the effects normally have, so it "calls" whatever happens to be the key%64K, which often results in crashes. Basically, the effects are OK, they just need more "key-space".
=> Expand effects to be beyond 64K limit

src/filesystem/simple_fs_nix.cpp
according to https://man7.org/linux/man-pages/man2/posix_fadvise.2.html posix_fadvice can tell the kernel to load pages beforehand for the specified file - may help to improve performance
=> use posix_fadvise to map files beforehand

src/common_types/constants.hpp, src/gamestate/commands.cpp, src/gamestate/commands.hpp, src/gamestate/system_state.cpp, src/gui/gui_chat_window.hpp, src/gui/gui_graphics.hpp, src/gui/gui_minimap.hpp
doesn't add anything multiplayer - you can talk to yourself on singleplayer :)
i used the in-game lobby window instead of the "normal" chat window, mainly because:
a) the ingame lobby window provides kick buttons and a list of all the players (useful for QoL features like kicking and banning in-game)
b) provides the chat log in a window that can be toggled with <TAB>
c) of course it is hidden at the start of the game, but on mutliplayer we should maybeeeeee show it at the start, as it is important in multiplayers
=> Chat window

assets/alice.csv, src/gamestate/commands.cpp, src/gamestate/commands.hpp, src/gui/gui_nation_picker.hpp
- why have ban and kick, why not only ban/kick?
- ban -> prevent people from rejoining
- kick -> to kick people from the lobby [but not disallow them from rejoining]
=> Ban and kick buttons and commands

assets/alice.csv, docs/contributing.md, docs/multiplayer.md, src/gamestate/commands.cpp, src/gamestate/commands.hpp, src/gamestate/serialization.cpp, src/gamestate/system_state.cpp, src/gamestate/system_state.hpp, src/gui/gui_chat_window.hpp, src/gui/gui_nation_picker.hpp, src/gui/topbar_subwindows/military_subwindows/gui_build_unit_large_window.hpp
- fix chat message crash when long message
- improve multiplayer handling of savefiles (on nation picker, "PLAY" button will be greyed out if checksum doesn't match)
- provide checksumming everytime a save is loaded or when a client connects so we dont enter into an invalid game state that breaks everything
rationale for having two checksums:
1. is for scenario, scenario checks for savefiles and whatnot
2. the other is for the session, meant to be to check if a client can interact with the game state of a host properly
=> misc fixes

src/common_types/constants.hpp, src/gui/gui_element_types.cpp, src/gui/gui_graphics.hpp, src/gui/gui_topbar.hpp, src/gui/topbar_subwindows/gui_production_window.hpp, src/gui/topbar_subwindows/gui_trade_window.hpp, src/gui/topbar_subwindows/politics_subwindows/gui_decision_window.hpp, src/parsing/econ_parsing.cpp, src/parsing/gui_graphics_parsers.cpp
- add industrial_and_consumer_goods commodity group
- respective UI accomodations for said category
- scaling factor of "25" added, using an unused bit of the scrollbar flags to not interfere with existing infrastructure
- decision names can now come in colours (HPMP outlined a red decision btw!) and a lot of mods use this colouring too!
=> UI accomodations for VU fork

src/parsing/nations_parsing.cpp, src/parsing/parser_defs.txt, src/parsing/parsers_declarations.cpp, src/parsing/parsers_declarations.hpp
so we have decision "utility_dec", so alice searches for "utility_dec" but, sike! it doesn't have a picture, so it defaults to noimage.tga,
ok so, what happens when a bunch of decisions have this image? you start to get suspicious of the behaviour, so you start investigating and, what? you find that the picture field of decisions is ignored on parsing, sus amongus
now the sussy baka is found, it is time for emergency meeting to oust the imposter, so we find, it indeed, `picture = cogs_blue`, and what do we find? cogs_blue.tga, AHA!!! so now we found the amongus crewmate imposter, we found it we are the sussiest baka ever
now after we finally realize that decision images are broken, we fix them and then the imposter is gone and the sussy baka is restored
=> fix decision pictures not getting shewn

src/military/military.cpp
p_factor seems too big and causing thousands of prestige gain/losses during crisises
the magic number of 0.05 is not a nice solution and overall this part of code needs rework based on reverse-engeneering
=> fixing the amount of prestige gain/loss during crisis peaceful resolution

src/gamestate/system_state.cpp, src/parsing/parser_defs.txt, src/parsing/parsers_declarations.hpp, tests/scenario_building.cpp
supports diplomacy files like `history/diplomacy/Japan.txt` yknow, since, yknow, HFM, and HPM, yknow
=> support spreaded diplomacy files

assets/alice.csv, assets/alice.gui, assets/shaders/msaa_f_shader.glsl, src/gamestate/system_state.cpp, src/gamestate/system_state.hpp, src/gui/gui_main_menu.cpp, src/gui/gui_main_menu.hpp, src/map/map.cpp
Makes stuff smoother,
limited to [1, 2], in increments of 0.125 - higher than that results in pretty much not very nice results for players.
Main usage: to make stuff seem a lot smoother than it is (MSAA already does this, but Guassian Blur makes things slightly more photographic in addition to MSAA, hence why it's needed to do MSAA first)
=> Gaussian blur map filter

dependencies/stb/stb_image.h, src/gamestate/system_state.hpp, src/main.cpp
As i understand it, the sys::state class doesnt manage its own resources. so it is not in need of a destructor declaration
=> fallthrough labels & removing destructor

src/culture/culture.hpp, src/ogl/texture.cpp
doesn't cost anything to add, plus it's just 4 slots, and allows me to not have to fiddle with `goverments.txt`
=> add slot(1,2,3,4) to support gfm dynamic dominion flags

src/window/window_nix.cpp, src/window/window_win.cpp
this makes the listed keypress events repeated events which is needed to have conventional text editing
=> repeat backspace, del and left, right, up and down arrow keypress events

src/economy/demographics.cpp, src/gui/topbar_subwindows/gui_population_window.hpp
Noticed that certain European nations were getting maxed plurality just a single decade into the game, UI and calculations seem to make consciousness gain from plurality/literacy be 10x as effective as what the UI states in Vic 2 so I adjusted it.
New adjustments
Vs Vic 2
=> Adjusts the consciousness algorithm to be consistent with Vic 2

src/gui/gui_outliner_window.hpp
- Reorganized the text per line to include more relevant information; reordered as the % of demographics that is the promoted pop followed by the NF used and finally the state name
- The state having more clergymen than the _**max_clergy_for_literacy**_ will be recolored red, copying vanilla behavior in warning the player that additional promotion is unproductive for the NF
=> Improves the National focus section of the outliner

src/gui/gui_element_types.cpp
original OpenV2 did this, why don't we?
=> display a white piechart instead of a black one

src/ai/ai.cpp, src/culture/rebels.cpp
Big list of changes
- Rebel AI can now properly form pan nationalist factions, although nationalists still appear to be broken, this should drastically increase the chance of an Italy appearing alongside the occasional Gutter crown for the germans
- Nations will try to unally and desphere countries they have wargoals against; stops certain situations like USA sphering mexico causing them to not be able to manifest a destiny
- Modified some tech weights, effective outcome should be a much higher focus on national focus techs, culture and army
- Redid the sphere AI; now tries to not sphere countries they don't have a neighboring sphere or a coastal state to access. Countries will now hyperfocus on sphering countries within their culture union
- AI will now intervene in wars even if they're …
=> Nationalism AI; changes for encouraging more nationalism to successfully suceed

src/entry_point_nix.cpp
Since the Linux version doesn't support the launcher you have to run `Alice` from the command line and by default this won't load any scenario data resulting in an error. I copy-pasted the code from the Windows file equivalent so that when running `./Alice` with no other arguments will try to run the development scenario or build it if it isn't there. This way users can at least clone the repo on Linux, build, then run the base game. I haven't cross-compiled the launcher to create scenario files so I haven't tested running with modded scenarios.
Also changed the window creation parameters for parity with the Windows version.
=> Fix Linux build

src/text/text.hpp
GCC throws an `-fpermissive` error on these lines but clarifying the scope fixes the issue.
=> Fix compilation error

assets/alice.csv, src/gui/gui_map_legend.hpp, src/gui/gui_minimap.hpp, src/gui/map_tooltip.cpp, src/map/map_modes.cpp, src/map/map_modes.hpp, src/map/modes/religion.hpp
Adds mod support for a religion map mode (`mapmode_24`) that works in the same way as the cultural map mode although it *does not* actually add the button to activate the map mode into PA. The GUI needs modified to add a button for it by adding a block of code like this to `interface/menubar.gui`. Note that this code specifically reuses the naval map mode icon and it is out of place so further UI tweaking would be needed but the feature is there for UI mods.
```
guiButtonType = {
name = "mapmode_24"
position = { x = -62 y = -136 }
quadTextureSprite ="GFX_mapmode_naval"
Orientation = "LOWER_RIGHT"
clicksound = click
}
```
Pictures
=> Add support for a religion map mode

src/gui/gui_outliner_window.hpp
To make outliner more usual for people coming from base V2, it's relevant to include the influence points count in the outliner window.
=> Influence number in the outline

src/nations/nations.cpp
Reorder two lines to make sure that the overlord-vassal relation is broken before updating nation coloring, otherwise the newly-independent country will still be colored like it's a vassal.
=> Remove Overlord Color Influence on Devassalization

src/ai/ai.cpp
The laissez faire branch of the eco AI had a redundant else if condition that meant that the AI would never recognize that it was gaining money and adjust its budget accordingly. The non-LF AI didn't have this issue so I duplicated the conditions in the corresponding if-else statement.
=> Fix else if condition in economy AI

src/map/modes/migration.hpp
Makes countries with no net migration appear orangish instead of dark red, that way net emigration will appear reddish. Also changes the starting value of two floats to prevent an extremely unlikely chance of a division by 0.
=> Tweak migration map mode

src/gui/gui_console.cpp
i dont know what `state.ui_state.main_menu_win` is for. this change leaves only its declaration and initialization with `nullptr`. should maybe be removed.
=> make mainmenu command toggle mainmenu instead of triggering sigsegv

src/ai/ai.cpp
Fixing what looks like a copy-paste error where the AI only fabricates CBs against its rival. `n.get_ai_rival()` also could be invalid here anyways since it's in the else branch of the `if(n.get_ai_rival() && ,,,)` check.
=> Fix incorrect AI CB fabrication target

src/gui/topbar_subwindows/gui_diplomacy_window.hpp, src/military/military.cpp
A casus belli gives a war its name, usually something like `WAR_CONQUEST_ANY_NAME` which looks up a localization string `NORMAL_WAR_CONQUEST_ANY_NAME`, but Victoria 2 also had a feature where you can specify a localization string `NORMAL_WAR_CONQUEST_ANY_NAME_ABC_DEF` which, if there was a war where the primary attacker had the tag `ABC` and the primary defender had the tag `DEF`, would give that specific war the name specified in the localization file for that combination of tags, otherwise it would default to the usual war name if there wasn't any. Mods like HPM used this for wars like the Oriental Crisis and European intervention against Egypt for example.
This feature has been implemented, although the code isn't the prettiest since it needs to look up the raw localization tag instead …
=> Add ability to name wars based on belligerents

src/gui/gui_map_icons.hpp
before defender casualties could appear in the wrong position because it wasn't getting right the player_is_attacker value
=> fixed casualties bug

src/gui/gui_topbar.hpp, src/nations/nations.cpp, src/nations/nations.hpp
The contents of max_colonial_points() and free_colonial_points() functions have been separated into functions in the same namespace so they can be called in a way that looks intuitive for the newly added details in gui_topbar, instead of basically repeating the contents of nations.cpp there
The csv file needs to be updated with some text keys because as you have seen my computer is messing it up. It will work fine without them so I can add them later if you don't want to
explain_colonial_points;Secondary and Great Powers accumulate colonial points.
colonial_points_from_technology;From technologies:
colonial_points_from_naval_bases;From naval bases:
colonial_points_from_ships;From ships:
used_colonial_maintenance;Maintaining existing colonies:
=> Colonial power tooltip detail added

src/culture/rebels.cpp, src/text/text.cpp, src/text/text.hpp
Re-adding support for $COUNTRY_ADJ$ as a rebel name token since that was something that Victoria 2 had then also added in support for a $RELIGION$ token since that type of rebel group is supported (although I'm not sure what the V2 token was since it was never really used).
=> Add support for COUNTRY_ADJ and RELIGION tokens in rebel names

src/economy/economy.cpp
Bounding the social spending slider instead of the domestic investment one.
=> Fix incorrect budget slider constraint

assets/alice.csv, src/gui/map_tooltip.cpp, src/map/map_modes.cpp
Adds missing tooltips for the new mapmodes
Fort - Shows fort level and building options
Ideology - Shows ideologies by pop, same as pie chart
Income - Shows total income of all pops in state
Consciousness - Shows consciousness and what's affecting it, same as revolt risk with militancy
Militancy - N/A, it's duplicate of revolt risk mode
Literacy - Literacy of pops
Employment - Shows percentage employed. This is out of employable pops not total pops, which excludes soldiers etc. Changed the map mode to use employable as well
Factories - Shows number of factories in state as well, as well as factory types and their levels. Changed the map mode to handle factories in split states
Issues - Shows top 5 issues from all pops, same as pie chart
Growth - Shows monthly growth, map mode is two …
=> Map mode tooltips

assets/alice.csv, src/gui/map_tooltip.cpp, src/map/map_modes.cpp, src/map/modes/revolt.hpp
Make revolt map mode show revolts, and militancy map show militancy
Revolt shows total population per province that are part of any rebel group
Tooltip breaks down total rebels by rebel group
=> Revolt map mode

src/common_types/container_types.hpp
[will most likely not work after unicode transition - but this will do for now]
=> Truncate whitespace from player names (used on GUI mostly)

assets/alice.csv, src/gui/gui_topbar.hpp
Changed so it's more alike vic2, displays the same info as before + a "total population" which is 4x the real population, as asked in #feature-requests by @Nosillew.
Also added some color which looks more cool imo:
Before:
After:
=> Changed the population tooltip

src/ai/ai.cpp
- AI will now join crisis with colonial concessions and such
- Will also send peace offers accordingly at max crisis temperature, because:
- a) Going to war will make them lose more than they win (given the economy)
- b) If the other side accepts, then it's best for the AI
- c) If the other side declines, we go to war faster, indeed, but if we are superior in strength and we demanded terms, we will likely win
- d) And if not, then it's probably because the other side wants to go to war anyways so yeah
=> AI improve behaviour on PO of crisis

docs/user_guide.md
I managed to get Project Alice to run on PopOS. I did it by using Lutris and [this guide](https://forums.lutris.net/t/very-brief-tutorial-on-manually-installing-a-game-in-lutris/2028). The setup is the same as for Windows, the new thing is how you run it using Lutris. For the Wine version, I used the one that was already pre-installed, so I didn't fiddle with that.
I also managed to load up the mod Divergences of Darkness. I have not yet tried Multiplayer but I will at some point.
This is the formal commit for that.
=> Added Lutris installation instructions for Ubuntu/PopOS

assets/alice.csv, assets/alice.gui, src/ai/ai.cpp, src/gamestate/commands.cpp, src/gamestate/commands.hpp, src/gamestate/dcon_generated.txt, src/gui/gui_unit_panel.hpp
Enable/Disable AI control of this unit, the unit will:
- Automatically reinforce frontlines
- Automatically siege when it's safe to do so
- Hunt rebels
- Form a defensive position against nations we're likely to attack (this is at the AI's discretion, and only at peace time)
If you want to make this unit target a specific nation or region, first move it close to that region or nation, then turn on AI control - because the AI will override all of your commands until you turn it off again
=> Auto siege for units

src/gui/gui_unit_panel.hpp
]WIP DO NOT MERGE UNTIL I FINISH TESTING THANKS
=> split units when embarking feature

src/filesystem/simple_fs_win.cpp
this did indeed reduce load times significantly
atleast for my slow hdd
https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfileexw
FindExInfoBasic -> avoid querying data we dont want (like the short veersion of a file name)
FIND_FIRST_EX_LARGE_FETCH -> Uses a larger buffer for directory queries, which can increase performance of the find operation.
tested and doesnt break alice
=> Speedup file listing on windows

src/gui/gui_event.cpp
when a new event spawns, resetting the window position is useful as to not confuse the user why some windows appear moved
=> Reset event window position

src/gui/topbar_subwindows/gui_diplomacy_window.hpp
Just realized - when this window is created, state.local_player_nation is dcon::nation_id{}
=> Fix diplomacy window nation facts once and for all

src/ai/ai.cpp
AI does not build units if there is a unit in progress.
Units construction does not progress on occupied land.
So if there is a unit which they tried to build in the past on currently occupied land, they are stuck.
This PR tries to fix this oversight.
=> Small AI fix

docs/extensions.md, src/economy/economy.cpp, src/gamestate/dcon_generated.txt, src/gamestate/system_state.cpp, src/parsing/parser_defs.txt, src/parsing/parsers_declarations.hpp, src/parsing/provinces_parsing.cpp
Syntax is 
```
rgo_distribution = {
entry = {
trade_good = silk
max_employment = 100000
}
entry = {
trade_good = opium
max_employment = 100000
}
}
```
It overwrites values which would be otherwise generated by a game.
=> Implement `rgo_distribution` for province history.

src/gamestate/system_state.cpp
credit to arkusix on the discord for finding this. shouldn't break things on windows, although we are unable to test it ourselves
=> fix localisation issue on linux

src/map/map_data_loading.cpp
- Ported the structs and changed type used from DWORD into uint32_t, WORD into uint16_t, LONG into int32_t
- Removing ifdef part for _WIN64, adding ifdef part for \_\_linux\_\_ instead
- Tested with GFM (specifically pauils-africa-rework branch) and vanilla scenario
- Ported CIEXYZ structs for BITMAPV5HEADER
=> Linux: Provide decompression function for compressed bmp files

src/gamestate/commands.cpp, src/gui/topbar_subwindows/diplomacy_subwindows/gui_diplomacy_actions_window.hpp, src/parsing/defines.hpp
Introducing compatibility defines flag "alice_allow_subjects_declare_wars" to allow subjects declare wars and add wargoals in wars. Also rework of wrong ui logic with "has_any_usable_cb".
=> Defines flag to allow subjects declare wars

assets/localisation/ar-AR/alice.csv, assets/localisation/de-DE/alice.csv, assets/localisation/en-US/alice.csv, assets/localisation/es-ES/alice.csv, assets/localisation/it-IT/alice.csv, assets/localisation/nl-NL/alice.csv, assets/localisation/pl-PL/alice.csv, assets/localisation/ru-RU/alice.csv, assets/localisation/zh-CN/alice.csv, src/gui/gui_outliner_window.hpp, src/gui/topbar_subwindows/military_subwindows/gui_units_window.hpp
- When constructing melee unit, display province in the outliner
- When constructing naval unit, display province in the outliner
- Clicking on melee unit construction row in the outliner, navigate to the province
- Clicking on naval unit construction row in the outliner, navigate to the province
- When constructing melee unit, display unit type name in melee view
- When constructing naval unit, display unit type name in melee view
=> Unit construction outliner & queue improvements

src/common_types/prng.cpp
the approach the current code does is `float(x & 0xffff) / float(0xffff)`
but this is inefficient
this is a function to implement a better version of that same op
=> fast get_random_float()

src/map/map_state.cpp
Note: this way to render connection should be eventually redone as it leads to a lot of excess vertices in major ports. Proper way requires calculation of total trade sea balance and drawing a route between port and province depending on this volume while using separate (arrow-less) texture when sea trade is balanced.
=> Fix pathing order in render of trade routes.

src/economy/economy.cpp, src/economy/economy.hpp, src/nations/nations.cpp, src/parsing/defines.hpp
- Less greedy artisans
- Need weights are set to 1 to encourage consumption of actual goods instead of coal
- Cull trade routes more aggressively to avoid 1 Jan freeze
- Tweak some numbers
=> Economy balance tweaks

src/ai/ai.cpp, src/gamestate/serialization.hpp, src/parsing/defines.hpp
The name of the define is "alice_ai_strength_estimation_military_industrial_balance", and its default is "1.0" (which doesn't change it from its previous behavior for now, others may fine tune as wished.)
Also cleans up weird looking stuff in defines.hpp as well.
=> Add define to weigh between military and industrial power in ai::estimate_strength.

src/map/modes/political.hpp
Rebel occupation will be the color of the rebel ideology. Will be 127,127,127 when no ideology is specified for the rebels.
=> Rebel occupation reflects rebel ideology

src/gui/gui_element_types.cpp
In gui_element_types.cpp, in the rebel flag code.
=> (hopefully) prevent crash by removing untested and redundant code

src/military/military.cpp, src/military/military.hpp
This PR is meant to improve the selection of leaders in battles (ie who the game picks to be the leader, and apply their +atk and +def stats).
At the moment once a leader is chosen in a battle (whichever army starts the battle first), the leaders are more or less set in stone, and won't change even if a better leader is inserted together with another army. 
The PR changes the following regarding selection logic:
1: When a new army joins the battle, it will re-calculate all the leader scores in the battle, and select the one with the highest score. This enables the player to not have to worry about which army they have to insert "first", as any "Better" generals will automatically take over once inserted.
2: The leader score calculation is changed so that it will ignore the opposite stat, …
=> Improving leader selection in land and naval battles

enc_temp_folder/d117bd389f5bd8931bff7b02cd868cc/gui_unit_panel.hpp, src/ai/ai.cpp, src/gui/gui_land_combat.hpp, src/gui/gui_leader_select.hpp, src/gui/gui_leader_tooltip.cpp, src/gui/gui_naval_combat.hpp, src/gui/gui_unit_panel.hpp, src/gui/topbar_subwindows/military_subwindows/gui_leaders_window.hpp, src/gui/topbar_subwindows/military_subwindows/gui_units_window.hpp, src/military/military.cpp, src/military/military.hpp, src/parsing/military_parsing.cpp
The purpose of this PR is to make minor visual improvements to "no-leader"'s (when you don't have a general or admiral selected), and enable its scriptabillity as is the case in base Vic2. The PR does the following:
1. Enables the traits of "no-leader" to be scriptable as it is in vic2, it will use the first personality trait, and the first background trait to apply the maluses (in base vic2 this means a -2 atk, -2 def malus, but it can easily be changed by a simple vic2 mod by changing traits.txt)
2. Makes minor visual improvements to how no-leaders are presented, such as writing the the value of the "no_leader" localisation key whenever a general name would be written instead, and allows the user to see the maluses of a no-leader by hovering over it, either in the army window or in a …
=> Minor no-leader improvements

src/military/military.cpp
Bugfix fixing incorrect leader selection (friendly leader might end up leading the enemy side, and vice versa) if one of the participants in the battle is in multiple wars at the same time, due to faulty logic in determining who is the attacker of the battle.
=> Leader selection fix

src/economy/economy.cpp, src/economy/economy.hpp, src/economy/economy_government.cpp, src/economy/economy_production.cpp, src/economy/economy_production.hpp, src/economy/economy_stats.cpp, src/gamestate/system_state.hpp, src/gui/economy_viewer.cpp, src/gui/gui_common_elements.hpp, src/gui/gui_province_window.hpp, src/gui/gui_topbar.hpp, src/gui/immediate_mode.hpp, src/gui/topbar_subwindows/gui_production_window.hpp, src/parsing/defines.hpp, src/scripting/fif_triggers.cpp, src/scripting/triggers.cpp
- Make trade routes more stable.
- Reduce demand on labor in states without corresponding labor
- Fix bug related to employment of craftsmen
- Numerous numerical tweaks
- New tab in economy scene: wages
- Removal of everyday tier subsistence
- Relax "job available" trigger to help craftsmen to increase their numbers
=> Economy rebalance and bugfixes

assets/shaders/glsl/map_sprite_f.glsl, assets/shaders/glsl/map_sprite_v.glsl, src/map/map.cpp, src/map/map.hpp, src/map/map_state.cpp
Implements the following feature:
After selecting a trade good to examine trade routes around the world, the game will spawn moving sprites which will follow trade routes according to throughput of the routes and eventually despawn them in places where incoming trade volume is larger that outgoing trade volume
=> New trade animation.

assets/localisation/en-US/alice.csv, src/ai/ai.cpp, src/economy/demographics.cpp, src/economy/demographics.hpp, src/economy/economy.cpp, src/economy/economy_government.cpp, src/gui/alice_ui.cpp, src/gui/pop_details.cpp
- Add additional multiplier to increase a chance of migration to province with high wage
- Add base chance for primary culture bureaucracy to migrate to problematic regions (resolves issues with far away regions with diverging administration costs)
- Use state capital bureaucracy instead of provincial one (has to be done as bureaucracy does not migrate to random provinces)
- Minor fix for trade: allow trade if at least one party unlocked related commodity
=> Small adjustments to migration and bureacracy.

src/economy/economy.cpp, src/economy/economy.hpp, src/parsing/defines.hpp, src/provinces/province.cpp
Use "needs satisfaction" as an estimation of "current consumption level" which generates base multipliers for demand.
=> Change demand calculations.

src/economy/economy.cpp, src/gamestate/commands.cpp, src/gui/gui_nation_picker.hpp, src/network/network.cpp
This PR refactors the economy.cpp getter+setters into proper setters, and fixes a bug i stumbled upon in which naval consumption was added to army_demand instead of navy_demand.
It adds an additional safeguard in commands to ensure that it is not possible to stop/start a game while a client is loading (as this can lead to desyncs).
Removed some out-of-date text including a tooltip on the "start" button for the client which warned against a checksum mismatch. It now does a checksum/oos check when a client joins instead.
Removed the "host has reloated players" text message being sent when a reload is initiated. This was initially used for automatic resyncing, but has since been replaced by manual resyncing.
=> Refactor economy.cpp getters, fix misc. MP stuff

assets/localisation/zh-CN/alice.csv
Added new localisation entries in zh-CN for province victory points and related scoring factors, enhancing in-game clarity for Chinese-speaking users.
=> Add Chinese translations for province victory points

src/gamestate/commands.cpp, src/gamestate/serialization.cpp, src/gamestate/system_state.cpp, src/gamestate/system_state.hpp, src/gui/gui_topbar.hpp
Store player cache variables for all played nations so on resync (when the host sends the savegame to clients) they keep the history of treasury and population.
=> Multi-player player cache

src/network/network.cpp
Fixes an issue discovered by @SneakBug8 in which batch commands which were dependent on eachother (such as peacedeals) would get wrongfully invalidated as all commands in a batch would be validated prior to the execution of any of the commands.
Commands are still validated right before execution in ```send_and_recieve_commands```. This just removes the pre-emptive validation which happend when the host first recieves the command from clients. Also renames a function to better convey its purpose
=> Fix pre-emptive command validation in MP
